var country  = [
  { id: "AF", name: "AFGHANISTANA 阿富汗" },
  { id: "ALB", name: "ALBANIA 阿尔巴尼亚" },
  { id: "DZA", name: "ALGERIA 阿尔及利亚" },
  { id: "AD", name: "ANDORRA 安道尔" },
  { id: "AO", name: "ANGOLA 安哥拉" },
  { id: "AG", name: "ANTIGUABARBUDA 安提瓜和巴布达" },
  { id: "ARG", name: "ARGENTINA 阿根廷" },
  { id: "AM", name: "ARMENIA 亚美尼亚" },
  { id: "AUS", name: "AUSTRALIA 澳大利亚" },
  { id: "AT", name: "AUSTRIA 奥地利" },
  { id: "AZE", name: "AZERBAIJAN 阿塞拜疆共和国" },
  { id: "AIA", name: "Anguilla 安圭拉" },
  { id: "BS", name: "BAHAMAS 巴哈马" },
  { id: "BHR", name: "BAHRAIN 巴林" },
  { id: "BD", name: "BANGLADESH 孟加拉国" },
  { id: "BB", name: "BARBADOS 巴巴多斯" },
  { id: "BY", name: "BELARUS 白俄罗斯" },
  { id: "BEL", name: "BELGIUM 比利时" },
  { id: "BZ", name: "BELIZE 伯里兹" },
  { id: "BJ", name: "BENIN 贝宁" },
  { id: "BT", name: "BHUTAN 不丹" },
  { id: "BOL", name: "BOLIVIA 玻利维亚" },
  { id: "BIH", name: "BOSNIA 波斯尼亚和黑塞哥维那" },
  { id: "BWA", name: "BOTSWANA 博茨瓦纳" },
  { id: "BRA", name: "BRAZIL 巴西" },
  { id: "BN", name: "BRUNIDARUSSALAM 文莱达鲁萨兰国" },
  { id: "BGR", name: "BULGARIA 保加利亚" },
  { id: "BFA", name: "BURKINAFASO 布基纳法索" },
  { id: "BI", name: "BURUNDI 布隆迪" },
  { id: "BMU", name: "Bermuda 百慕大群岛" },
  { id: "BTN", name: "Bhutan 不丹" },
  { id: "KHM", name: "CAMBODIA 柬埔寨" },
  { id: "CMR", name: "CAMEROON 喀麦隆" },
  { id: "CA", name: "CANADA 加拿大" },
  { id: "KY", name: "CAPEVERDE 佛得角" },
  { id: "CF", name: "CENTRALAFRICANREPUBLI 中非共和国" },
  { id: "TD", name: "CHAD 乍得" },
  { id: "CL", name: "CHILE 智利" },
  { id: "CHN", name: "CHINA 中国" },
  { id: "COL", name: "COLOMBIA 哥伦比亚" },
  { id: "KM", name: "COMOROS 科摩罗" },
  { id: "CG", name: "CONGO 刚果（布）" },
  { id: "COD", name: "CONGO, THE DRC (Kinshasa) 刚果(金沙萨)" },
  { id: "CK", name: "COOKISLANDS 库克群岛" },
  { id: "CRI", name: "COSTA RICA 哥斯达里加" },
  { id: "CIV", name: "COTEDLVOIRE 科特迪瓦" },
  { id: "HRV", name: "CROATIA 克罗地亚" },
  { id: "CUB", name: "CUBA 古巴共和国" },
  { id: "CYP", name: "CYPRUS 塞浦路斯" },
  { id: "CZ", name: "CZECHREPUBLIC 捷克共和国" },
  { id: "YD", name: "DEMOCRATICYEMEN 也门民主人民共和国" },
  { id: "DK", name: "DENMARK 丹麦" },
  { id: "DJI", name: "DJIBOUTI 吉布提" },
  { id: "DMA", name: "DOMINICA 多米尼克" },
  { id: "DOM", name: "DOMINICANREPUBLIC 多米尼加共和国" },
  { id: "EC", name: "ECUADOR 厄瓜多尔" },
  { id: "EGY", name: "EGYPT 埃及" },
  { id: "SV", name: "ELSALVADOR 萨尔瓦多" },
  { id: "GBR", name: "ENGLAND 英国" },
  { id: "GQ", name: "EQUATORIALGUINEA 赤道几内亚" },
  { id: "ERI", name: "ERITREA 厄立特里亚" },
  { id: "EE", name: "ESTONIA 爱沙尼亚" },
  { id: "ETH", name: "ETHIOPIA 埃塞俄比亚" },
  { id: "FO", name: "FAROEISLANDS 法罗群岛" },
  { id: "FK", name: "FAULKLANDISLANDS 福克兰群岛" },
  { id: "FJI", name: "FIJI 斐济" },
  { id: "FIN", name: "FINLAND 芬兰" },
  { id: "WF", name: "FORTUNAISLANDS 瓦利斯和富图纳群岛" },
  { id: "FRA", name: "FRANCE 法国" },
  { id: "PF", name: "FRENCH POLYNESIA 法属波利尼西亚" },
  { id: "GF", name: "FRENCHGUIANA 法属圭亚那" },
  { id: "GAB", name: "GABON 加蓬" },
  { id: "GMB", name: "GAMBIA 冈比亚" },
  { id: "GEO", name: "GEORGIA 格鲁吉亚" },
  { id: "DE", name: "GERMAN Y德国" },
  { id: "GHA", name: "GHANA 加纳" },
  { id: "GRC", name: "GREECE 希腊" },
  { id: "GL", name: "GRENADA 格林纳达" },
  { id: "GN", name: "GUINEA 几内亚" },
  { id: "GW", name: "GUINEABISSAU 几内亚比绍" },
  { id: "GY", name: "GUYANA 圭亚那" },
  { id: "GIB", name: "Gibraltar 直布罗陀" },
  { id: "GUM", name: "Guam (Mariana Islands) 关岛（马里亚纳群岛）" },
  { id: "GTM", name: "Guatemala 危地马拉" },
  { id: "NLD", name: "HOLLAND 荷兰" },
  { id: "HUN", name: "HUNGARY 匈牙利" },
  { id: "HTI", name: "Haiti 海地" },
  { id: "HND", name: "Honduras 洪都拉斯" },
  { id: "HKG", name: "Hong Kong,China 中国香港" },
  { id: "IS", name: "ICELAND 冰岛" },
  { id: "IND", name: "INDIA 印度" },
  { id: "IDN", name: "INDONESIA 印度尼西亚" },
  { id: "IRN", name: "IRAN 伊朗" },
  { id: "IQ", name: "IRAQ 伊拉克" },
  { id: "IE", name: "IRELAND 爱尔兰" },
  { id: "IL", name: "ISRAEL 以色列" },
  { id: "ITA", name: "ITALY 意大利" },
  { id: "ISL", name: "Iceland 冰岛" },
  { id: "JM", name: "JAMAICA 牙买加" },
  { id: "JPN", name: "JAPAN 日本" },
  { id: "JOR", name: "JORDAN 约旦" },
  { id: "KZ", name: "KAZAKHSTAN 哈萨克斯坦" },
  { id: "KEN", name: "KENYA 肯尼亚" },
  { id: "KG", name: "KIRGIZSTAN 吉尔吉斯共和国" },
  { id: "KR", name: "KOREA 韩国" },
  { id: "KP", name: "KOREADEMOCRATICREPUBL 朝鲜民主主义共和国" },
  { id: "KWT", name: "KUWAIT 科威特" },
  { id: "KGZ", name: "Kyrgyzstan 吉尔吉斯斯坦" },
  { id: "LAO", name: "LAOS 老挝" },
  { id: "LVA", name: "LATVIA 拉脱维亚" },
  { id: "LBN", name: "LEBANON 黎巴嫩" },
  { id: "LSO", name: "LESOTHO 莱索托" },
  { id: "LR", name: "LIBERIA 利比里亚" },
  { id: "LY", name: "LIBYA 利比亚" },
  { id: "LIE", name: "LIECHTENSTEIN 列支敦士登" },
  { id: "LT", name: "LITHUANIA 立陶宛" },
  { id: "LUX", name: "LUXEMBOURG 卢森堡" },
  { id: "LTU", name: "Lithuania 立陶宛" },
  { id: "MK", name: "MACEDONIA 马其顿" },
  { id: "MG", name: "MADAGASCAR 马达加斯加" },
  { id: "MYS", name: "MALAYSIA 马来西亚" },
  { id: "MV", name: "MALDIVES 马尔代夫" },
  { id: "MLI", name: "MALI 马里" },
  { id: "MT", name: "MALTA 马耳他" },
  { id: "MQ", name: "MARTINIQUE 马提尼克" },
  { id: "MR", name: "MAURITANIA 毛里塔尼亚" },
  { id: "MUS", name: "MAURITIUS 毛里求斯" },
  { id: "MX", name: "MEXICO 墨西哥" },
  { id: "FM", name: "MICRONESIA 密克罗尼西亚联邦" },
  { id: "MD", name: "MOLDOVA 摩尔多瓦" },
  { id: "MC", name: "MONACO 摩纳哥" },
  { id: "MN", name: "MONGOLIA 蒙古" },
  { id: "MA", name: "MOROCCO 摩洛哥" },
  { id: "MZ", name: "MOZAMBIQUE 莫桑比克" },
  { id: "MMR", name: "MYANMAR 缅甸" },
  { id: "MYT", name: "Ma Mayotte 马约特岛" },
  { id: "MO", name: "Macao,China 中国澳门" },
  { id: "MHL", name: "Marshall Islands 马绍尔群岛" },
  { id: "MRT", name: "Mauritania 毛利塔尼亚" },
  { id: "MSR", name: "Montserrat 蒙特赛拉特岛" },
  { id: "NA", name: "NAMIBIA 纳米比亚" },
  { id: "NRU", name: "NAURU 瑙鲁" },
  { id: "NPL", name: "NEPAL 尼泊尔" },
  { id: "NZL", name: "NEWZEALAND 新西兰" },
  { id: "NER", name: "NIGER 尼日尔" },
  { id: "NGA", name: "NIGERIA 尼日利亚" },
  { id: "NU", name: "NIUE纽埃" },
  { id: "MP", name: "NORTHERNMARIANAISLAND 北马里亚纳群岛" },
  { id: "NOR", name: "NORWAY 挪威" },
  { id: "NAM", name: "Namibia 纳米比亚" },
  { id: "NCL", name: "New Caledonia Islands 新喀里多尼亚群岛" },
  { id: "NIC", name: "Nicaragua 尼加拉瓜" },
  { id: "NFK", name: "Norfolk Island 诺福克岛" },
  { id: "OMN", name: "OMAN 阿曼" },
  { id: "PK", name: "PAKISTAN 巴基斯坦" },
  { id: "PW", name: "PALAU 帕劳" },
  { id: "PG", name: "PAPUANEWGUINEA 巴布亚新几内亚" },
  { id: "PY", name: "PARAGUAY 巴拉圭" },
  { id: "PER", name: "PERU 秘鲁" },
  { id: "PHL", name: "PHILIPPINES 菲律宾" },
  { id: "PL", name: "POLAND 波兰" },
  { id: "PT", name: "PORTUGAL 葡萄牙" },
  { id: "PAN", name: "Panama 巴拿马" },
  { id: "PRI", name: "Portugal 波多黎各" },
  { id: "QAT", name: "QATAR 卡塔尔" },
  { id: "MAT", name: "ROMANIA 罗马尼亚" },
  { id: "RU", name: "RUSSIA 俄罗斯" },
  { id: "RWA", name: "RWANDA 卢旺达" },
  { id: "REU", name: "Reunion 留尼旺岛" },
  { id: "RUS", name: "Russian Federation 俄罗斯联邦" },
  { id: "LCA", name: "SAINTLUCIA 圣卢西亚" },
  { id: "WS", name: "SAMOA 美属萨摩亚" },
  { id: "SMR", name: "SANMARINO 圣马力诺" },
  { id: "STP", name: "SAOTOMEPRINCIPE 圣多美和普林西比" },
  { id: "SAU", name: "SAUDIARABIA 沙特阿拉伯" },
  { id: "SN", name: "SENEGAL 塞内加尔" },
  { id: "RS", name: "SERBIA 塞尔维亚" },
  { id: "SC", name: "SEYCHELLES 塞舌尔" },
  { id: "SLE", name: "SIERRALEONE 塞拉利昂" },
  { id: "SGP", name: "SINGAPORE 新加坡" },
  { id: "SK", name: "SLOVAKREPUBLIC 斯洛伐克共和国" },
  { id: "SI", name: "SLOVENIA 斯洛文尼亚" },
  { id: "SB", name: "SOLOMONISLANDS 所罗门群岛" },
  { id: "SOM", name: "SOMALI索马里" },
  { id: "ZAF", name: "SOUTHAFRIC A南非" },
  { id: "ESP", name: "SPAIN 西班牙" },
  { id: "LKA", name: "SRILANKA 斯里兰卡" },
  { id: "PM", name: "ST.PIERREANDMIQUELON 圣皮埃尔和密克隆" },
  { id: "SDN", name: "SUDAN 苏丹" },
  { id: "SR", name: "SURINAM 苏里南" },
  { id: "SZ", name: "SWAZILAND 斯威士兰" },
  { id: "SE", name: "SWEDEN 瑞典" },
  { id: "CHE", name: "SWITZERLAND 瑞士" },
  { id: "SYR", name: "SYRIA 叙利亚" },
  { id: "VCT", name: "Saint Vincent andtheGrenadines 圣文森特和格林纳丁斯" },
  { id: "WSM", name: "Samoa 萨摩亚群岛" },
  { id: "TJK", name: "TAJIKISTAN 塔吉克斯坦" },
  { id: "TZA", name: "TANZANIA 坦桑尼亚" },
  { id: "TH", name: "THAILAND 泰国" },
  { id: "TLS", name: "TIMOR东帝汶" },
  { id: "TGO", name: "TOGO 多哥" },
  { id: "TO", name: "TONGA 汤加" },
  { id: "TTO", name: "TRINIDADANDTOBAGO 特立尼达和多巴哥" },
  { id: "TN", name: "TUNISIA 突尼斯" },
  { id: "TR", name: "TURKEY 土耳其" },
  { id: "TM", name: "TURKMENISTAN 土库曼斯坦" },
  { id: "TV", name: "TUVALU 图瓦卢" },
  { id: "TWN", name: "Taiwan,China 中国台湾" },
  { id: "YEM", name: "The Republic of Yemen 也门共和国" },
  { id: "VAT", name: "The Vatican 梵蒂冈" },
  { id: "TCA", name: "Turks and Caicos Islands 特克斯和凯科斯群岛" },
  { id: "UGA", name: "UGANDA 乌干达" },
  { id: "UA", name: "UKRAINE 乌克兰" },
  { id: "USA", name: "UNITED STATES 美国" },
  { id: "UY", name: "URUGUAY 乌拉圭" },
  { id: "UZB", name: "UZBEKISTAN 乌兹别克斯坦" },
  { id: "AE", name: "United Arab Emirates 阿拉伯联合酋长国" },
  { id: "VU", name: "VANUATU 瓦努阿图" },
  { id: "VEN", name: "VENEZUELA 委内瑞拉" },
  { id: "VNM", name: "VIETNAM 越南" },
  { id: "VGB", name: "Virgin Islands (British) 维尔京群岛（英属）" },
  { id: "VIR", name: "Virgin Islands (U.S.) 维尔京群岛（美属）" },
  { id: "ZR", name: "ZAIRE 扎伊尔" },
  { id: "ZMB", name: "ZAMBIA 赞比亚" },
  { id: "ZWE", name: "ZIMBABWE 津巴布韦" }
];
